[general]
live_config_reload = true
ipc_socket = true

[env]

[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 1, y = 1 }
opacity = 0.9

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Menlo", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 17.25