# https://supercodepower.com/train-MIUI-OS
adb shell pm uninstall --user 0  com.android.browser
adb shell pm uninstall --user 0  com.android.email
adb shell pm uninstall --user 0  com.android.providers.downloads.ui
adb shell pm uninstall --user 0  com.android.quicksearchbox
adb shell pm uninstall --user 0  com.baidu.input_mi
adb shell pm uninstall --user 0  com.mfashiongallery.emag  
adb shell pm uninstall --user 0  com.mi.liveassistant
adb shell pm uninstall --user 0  com.milink.service
adb shell pm uninstall --user 0  com.miui.analytics
adb shell pm uninstall --user 0  com.miui.contentextension
adb shell pm uninstall --user 0  com.miui.hybrid.accessory
adb shell pm uninstall --user 0  com.miui.miservice
adb shell pm uninstall --user 0  com.miui.mishare.connectivity
adb shell pm uninstall --user 0  com.miui.newhome
adb shell pm uninstall --user 0  com.miui.newmidrive
adb shell pm uninstall --user 0  com.miui.notes 
adb shell pm uninstall --user 0  com.miui.personalassistant
adb shell pm uninstall --user 0  com.miui.phrase
adb shell pm uninstall --user 0  com.miui.player
adb shell pm uninstall --user 0  com.miui.screenrecorder
adb shell pm uninstall --user 0  com.miui.smarttravel
adb shell pm uninstall --user 0  com.miui.systemAdSolution
adb shell pm uninstall --user 0  com.miui.translation.kingsoft
adb shell pm uninstall --user 0  com.miui.userguide
adb shell pm uninstall --user 0  com.miui.video
adb shell pm uninstall --user 0  com.miui.virtualsim
adb shell pm uninstall --user 0  com.miui.voiceassist
adb shell pm uninstall --user 0  com.miui.voicetrigger
adb shell pm uninstall --user 0  com.miui.yellowpage
adb shell pm uninstall --user 0  com.xiaomi.ab
adb shell pm uninstall --user 0  com.xiaomi.aiasst.service
adb shell pm uninstall --user 0  com.xiaomi.mibrain.speech
adb shell pm uninstall --user 0  com.xiaomi.mimobile.noti
adb shell pm uninstall --user 0  com.xiaomi.mirror
adb shell pm uninstall --user 0  com.xiaomi.payment
adb shell pm uninstall --user 0  com.xiaomi.scanner
adb shell pm uninstall --user 0  com.xiaomi.smarthome
